### ISSUE TITLE
Make TypeScript work out of the box

### ISSUE THREAD

**Issue by superoo7** [superoo7/vue-cli-plugin-chrome-ext#2]
Current build will caused TypeScript errors. User need to update the code, it doesnt work out of the box

**Comment by k1nghat** [comment]
is this what is causing this?:

> yarn build
yarn run v1.15.2
$ vue-cli-service build
 ERROR  Error loading vue.config.js:
 ERROR  TypeError: Class constructor CopyPlugin cannot be invoked without 'new'
TypeError: Class constructor CopyPlugin cannot be invoked without 'new'
    at Object.<anonymous> (/media/kinghat/kinghat-server/coding/projects/learning/javascript/misc/vue/vue-cli-plugin-chrome-ext/vue.config.js:35:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Service.loadUserOptions (/media/kinghat/kinghat-server/coding/projects/learning/javascript/misc/vue/vue-cli-plugin-chrome-ext/node_modules/@vue/cli-service/lib/Service.js:301:22)
    at Service.init (/media/kinghat/kinghat-server/coding/projects/learning/javascript/misc/vue/vue-cli-plugin-chrome-ext/node_modules/@vue/cli-service/lib/Service.js:73:30)
    at Service.run (/media/kinghat/kinghat-server/coding/projects/learning/javascript/misc/vue/vue-cli-plugin-chrome-ext/node_modules/@vue/cli-service/lib/Service.js:206:10)
    at Object.<anonymous> (/media/kinghat/kinghat-server/coding/projects/learning/javascript/misc/vue/vue-cli-plugin-chrome-ext/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
